# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=1.0.0
group=com.blockypenguin.mods.mod_template
java_version=21
# Common
minecraft_version=1.21.8
mod_name=ModTemplate
mod_author=BlockyPenguin
mod_id=mod_template
license=MIT
credits=
description=Line 1\nLine 2\nLine 3
minecraft_version_range=[1.21.8, 1.22)
issue_tracker_url=https://mods.blockypenguin.com/mod_template/issues
homepage_url=https://mods.blockypenguin.com/mod_template
sources_url=https://mods.blockypenguin.com/mod_template/sources
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
# !! Or see https://github.com/ParchmentMC/Parchment/tags
parchment_minecraft=1.21.8
parchment_version=2025.07.20
# Fabric
fabric_version=0.129.0+1.21.8
fabric_loader_version=0.16.14
loom_version=1.11-SNAPSHOT
# NeoForge https://neoforged.net/
neoforge_version=21.8.4-beta
neoforge_loader_version_range=[4,)
# https://projects.neoforged.net/neoforged/ModDevGradle
moddevgradle_version=2.0.103
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
